language: java
jdk:
- openjdk11

addons:
    sonarcloud:
        organization: "alepicco95"
        token: 
            secure: "a9eaac07a69a2abc74149f18f7abf015df305259"
        
script:
- ant build
- sonar-scanner
