language: java
jdk:
- openjdk11

addons:
    sonarcloud:
        organization: "alepicco95"
        token: 
            secure: "9851d6c03fe5bf6ad87c0a51c0d32d5c123a6709"
        
script:
- ant build
- sonar-scanner
