language: java
jdk:
- openjdk11

addons:
    sonarcloud:
        organization: "alepicco95"
        token: 
            secure: "98411d54d08a49b729fa755c29a6b8bd59f03452"
        
script:
- ant build
- sonar-scanner 
